# Generated by Django 3.0.7 on 2020-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20200622_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
