# Generated by Django 3.0.7 on 2020-06-22 16:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20200622_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='banner_title',
            field=models.CharField(blank=True, default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
