# Generated by Django 3.0.7 on 2020-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20200622_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselimages',
            name='caption',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
